package com.example.noflandrecipe.nofland_recipe_core;

import com.example.noflandrecipe.nofland_recipe_core.etype.*;
import com.example.noflandrecipe.nofland_recipe_core.model.*;

import java.util.ArrayList;
import java.util.List;

public class Initialization {
    private static final List<Item> ITEM_LIST = new ArrayList<>();
    private static final List<Recipe> RECIPE_LIST = new ArrayList<>();

    /*
      初始化材料
     */
    static {
        ITEM_LIST.add(new Item(1, "甜味黏土", itemType("素材"), habitat("山地"), collectPlace("乱石滩")));
        ITEM_LIST.add(new Item(2, "魔法冰泉", itemType("素材"), habitat("湖泊"), collectPlace("乱石滩")));
        ITEM_LIST.add(new Item(3, "火结晶", itemType("素材"), habitat("火山"), collectPlace("裂谷边缘")));
        ITEM_LIST.add(new Item(4, "微风粉尘", itemType("素材"), habitat("草原"), collectPlace("裂谷边缘")));
        ITEM_LIST.add(new Item(5, "彩虹羽翼", itemType("素材"), habitat("草原"), collectPlace("微风草原")));
        ITEM_LIST.add(new Item(6, "矿石碎片", itemType("素材"), habitat("山地"), collectPlace("落日山")));
        ITEM_LIST.add(new Item(7, "矿盐", itemType("素材"), habitat("湖泊"), collectPlace("乱石滩")));
        ITEM_LIST.add(new Item(8, "闪亮红砂", itemType("素材"), habitat("火山"), collectPlace("裂谷边缘")));
        ITEM_LIST.add(new Item(9, "棉雾气团", itemType("素材"), habitat("草原"), collectPlace("微风草原")));
        ITEM_LIST.add(new Item(10, "蜂蜡", itemType("素材"), habitat("草原"), collectPlace("乱石滩")));
        ITEM_LIST.add(new Item(11, "古树花粉", itemType("素材"), habitat("草原"), collectPlace("乱石滩")));
        ITEM_LIST.add(new Item(12, "铜簇", itemType("素材"), habitat("山地"), collectPlace("落日山")));
        ITEM_LIST.add(new Item(13, "晶海星", itemType("素材"), habitat("湖泊"), collectPlace("裂谷边缘")));
        ITEM_LIST.add(new Item(14, "液态滚石", itemType("素材"), habitat("火山"), collectPlace("火山")));
        ITEM_LIST.add(new Item(15, "妖精粉尘", itemType("素材"), habitat("草原"), collectPlace("微风草原")));
        ITEM_LIST.add(new Item(16, "刻金石板", itemType("素材"), habitat("山地"), collectPlace("裂谷边缘")));
        ITEM_LIST.add(new Item(17, "重水", itemType("素材"), habitat("湖泊"), collectPlace("碎溪流")));
        ITEM_LIST.add(new Item(18, "自燃石", itemType("素材"), habitat("火山"), collectPlace("火山")));
        ITEM_LIST.add(new Item(19, "深谷坚石", itemType("素材"), habitat("山地"), collectPlace("落日山")));
        ITEM_LIST.add(new Item(20, "息土", itemType("素材"), habitat("山地"), collectPlace("落日山")));
        ITEM_LIST.add(new Item(21, "古代页岩", itemType("素材"), habitat("山地"), collectPlace("落日山")));
        ITEM_LIST.add(new Item(22, "甲贝", itemType("素材"), habitat("湖泊"), collectPlace("碎溪流")));
        ITEM_LIST.add(new Item(23, "涤辰砂", itemType("素材"), habitat("湖泊"), collectPlace("碎溪流")));
        ITEM_LIST.add(new Item(24, "化石鱼骨", itemType("素材"), habitat("湖泊"), collectPlace("碎溪流")));
        ITEM_LIST.add(new Item(25, "深海结晶", itemType("素材"), habitat("湖泊"), collectPlace("碎溪流")));
        ITEM_LIST.add(new Item(26, "黑炭", itemType("素材"), habitat("火山"), collectPlace("火山")));
        ITEM_LIST.add(new Item(27, "干涸砂砾", itemType("素材"), habitat("火山"), collectPlace("火山")));
        ITEM_LIST.add(new Item(28, "日光石", itemType("素材"), habitat("火山"), collectPlace("火山")));
        ITEM_LIST.add(new Item(29, "坚硬的喙", itemType("素材"), habitat("草原"), collectPlace("微风草原")));
        ITEM_LIST.add(new Item(30, "生命之叶", itemType("素材"), habitat("草原"), collectPlace("微风草原")));
        ITEM_LIST.add(new Item(31, "魔法亓草种子", itemType("素材"), habitat("草原"), collectPlace("微风野地")));
        ITEM_LIST.add(new Item(32, "黄金小麦种子", itemType("素材"), habitat("草原"), collectPlace("微风野地")));
        ITEM_LIST.add(new Item(33, "折光兰种子", itemType("素材"), habitat("草原"), collectPlace("微风野地")));
        ITEM_LIST.add(new Item(34, "降雨水仙种子", itemType("素材"), habitat("山地"), collectPlace("陨坑边缘")));
        ITEM_LIST.add(new Item(35, "星辰珊瑚种子", itemType("素材"), habitat("山地"), collectPlace("陨坑边缘")));
        ITEM_LIST.add(new Item(36, "黑海带种子", itemType("素材"), habitat("山地"), collectPlace("陨坑边缘")));
        ITEM_LIST.add(new Item(37, "坚硬荆棘种子", itemType("素材"), habitat("湖泊"), collectPlace("微风野地")));
        ITEM_LIST.add(new Item(38, "干涸地蔓种子", itemType("素材"), habitat("湖泊"), collectPlace("微风野地")));
        ITEM_LIST.add(new Item(39, "风滚草种子", itemType("素材"), habitat("湖泊"), collectPlace("微风野地")));
        ITEM_LIST.add(new Item(40, "长明草种子", itemType("素材"), habitat("火山"), collectPlace("陨坑边缘")));
        ITEM_LIST.add(new Item(41, "辛辣辣椒种子", itemType("素材"), habitat("火山"), collectPlace("陨坑边缘")));
        ITEM_LIST.add(new Item(42, "火焰麦穗种子", itemType("素材"), habitat("火山"), collectPlace("陨坑边缘")));
        ITEM_LIST.add(new Item(1, "魔法亓草", itemType("生物"), habitat("草原"), collectPlace("种子培养架")));
        ITEM_LIST.add(new Item(2, "黄金小麦", itemType("生物"), habitat("草原"), collectPlace("种子培养架")));
        ITEM_LIST.add(new Item(3, "折光兰", itemType("生物"), habitat("草原"), collectPlace("种子培养架")));
        ITEM_LIST.add(new Item(4, "血浆果", itemType("生物"), habitat("火山"), collectPlace("果子培养架")));
        ITEM_LIST.add(new Item(5, "喷射孢子", itemType("生物"), habitat("山地"), collectPlace("腐朽树干")));
        ITEM_LIST.add(new Item(6, "幻梦菇", itemType("生物"), habitat("山地"), collectPlace("腐朽树干")));
        ITEM_LIST.add(new Item(7, "厄运蘑菇", itemType("生物"), habitat("山地"), collectPlace("腐朽树干")));
        ITEM_LIST.add(new Item(8, "降雨水仙", itemType("生物"), habitat("湖泊"), collectPlace("水培槽")));
        ITEM_LIST.add(new Item(9, "星辰珊瑚", itemType("生物"), habitat("湖泊"), collectPlace("水培槽")));
        ITEM_LIST.add(new Item(10, "黑海带", itemType("生物"), habitat("湖泊"), collectPlace("水培槽")));
        ITEM_LIST.add(new Item(11, "丛云果", itemType("生物"), habitat("草原"), collectPlace("水果培养架")));
        ITEM_LIST.add(new Item(12, "炽热蚯蚓", itemType("生物"), habitat("火山"), collectPlace("奇怪树干")));
        ITEM_LIST.add(new Item(13, "火溶虫", itemType("生物"), habitat("火山"), collectPlace("奇怪树干")));
        ITEM_LIST.add(new Item(14, "岩蛭", itemType("生物"), habitat("火山"), collectPlace("奇怪树干")));
        ITEM_LIST.add(new Item(15, "坚硬荆棘", itemType("生物"), habitat("山地"), collectPlace("山岩培养架")));
        ITEM_LIST.add(new Item(16, "干涸地蔓", itemType("生物"), habitat("山地"), collectPlace("山岩培养架")));
        ITEM_LIST.add(new Item(17, "风滚草", itemType("生物"), habitat("山地"), collectPlace("山岩培养架")));
        ITEM_LIST.add(new Item(18, "长明草", itemType("生物"), habitat("火山"), collectPlace("火山培养架")));
        ITEM_LIST.add(new Item(19, "辛辣辣椒", itemType("生物"), habitat("火山"), collectPlace("火山培养架")));
        ITEM_LIST.add(new Item(20, "火焰麦穗", itemType("生物"), habitat("火山"), collectPlace("火山培养架")));
        ITEM_LIST.add(new Item(21, "珍珠果", itemType("生物"), habitat("湖泊"), collectPlace("珊瑚培养架")));
        ITEM_LIST.add(new Item(22, "蜜虫", itemType("生物"), habitat("山地"), collectPlace("风蚀岩培养架")));
        ITEM_LIST.add(new Item(23, "龙卷斑蝶", itemType("生物"), habitat("山地"), collectPlace("风蚀岩培养架")));
        ITEM_LIST.add(new Item(24, "沙漠瓢虫", itemType("生物"), habitat("山地"), collectPlace("风蚀岩培养架")));
        ITEM_LIST.add(new Item(1, "增生土块", itemType("活动"), habitat("山地"), collectPlace("乱石滩")));
        ITEM_LIST.add(new Item(2, "海沟海蜇", itemType("活动"), habitat("湖泊"), collectPlace("微风草原")));
        ITEM_LIST.add(new Item(3, "月光石", itemType("活动"), habitat("草原"), collectPlace("陨坑边缘")));
        ITEM_LIST.add(new Item(4, "家族残徽", itemType("活动"), habitat("火山"), collectPlace("落日山")));
        ITEM_LIST.add(new Item(5, "冰髓", itemType("活动"), habitat("山地"), collectPlace("碎溪流")));
        ITEM_LIST.add(new Item(6, "不老冰", itemType("活动"), habitat("湖泊"), collectPlace("火山")));
        ITEM_LIST.add(new Item(7, "魔动环", itemType("活动"), habitat("草原"), collectPlace("火山")));
        ITEM_LIST.add(new Item(8, "魔魂残片", itemType("活动"), habitat("山地"), collectPlace("裂谷边缘")));
        ITEM_LIST.add(new Item(9, "生命枝杈", itemType("活动"), habitat("湖泊"), collectPlace("乱石滩")));
        ITEM_LIST.add(new Item(10, "衍生晶壤", itemType("活动"), habitat("火山"), collectPlace("陨坑边缘")));
        ITEM_LIST.add(new Item(11, "爆炸甲壳", itemType("活动"), habitat("火山"), collectPlace("碎溪流")));
        ITEM_LIST.add(new Item(12, "怪力药草", itemType("活动"), habitat("湖泊"), collectPlace("火山")));
        ITEM_LIST.add(new Item(13, "凝神圣水", itemType("活动"), habitat("草原"), collectPlace("火山")));
        ITEM_LIST.add(new Item(14, "膨胀木", itemType("活动"), habitat("山地"), collectPlace("裂谷边缘")));
        ITEM_LIST.add(new Item(15, "缩小宝石", itemType("活动"), habitat("湖泊"), collectPlace("乱石滩")));
        ITEM_LIST.add(new Item(16, "无风蛛网", itemType("活动"), habitat("火山"), collectPlace("陨坑边缘")));

    }

    /*
      初始化配方
     */
    static {
        RECIPE_LIST.add(new Recipe(1, "植物生长剂", recipeType("研制"), habitat("特殊"), new RecipeSell(10, 11, 12, 15, 0.933333f), new RecipeRecovery(2, 2, 2, 3), new RecipeItem(findItemByName("甜味黏土"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(1, "银阔拉", recipeType("调和"), habitat("特殊"), new RecipeSell(0, 0, 0, 1, 0f), new RecipeRecovery(0, 0, 0, 0), new RecipeItem(findItemByName("魔法亓草"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(1, "狮子的爪子", recipeType("秘方"), habitat("火山"), new RecipeSell(787, 865, 944, 300, 5.113333f), new RecipeRecovery(157, 173, 188, 236), new RecipeItem(findItemByName("晶海星"), 4, research("少量")), new RecipeItem(findItemByName("液态滚石"), 1, research("少量")), new RecipeItem(findItemByName("黄金小麦"), 1, research("少量")), new RecipeItem(findItemByName("血浆果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(1, "贴合剂", recipeType("活动"), habitat("特殊"), new RecipeSell(176, 193, 211, 130, 2.638462f), new RecipeRecovery(35, 38, 42, 52), new RecipeItem(findItemByName("增生土块"), 7, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 4, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(2, "催产肥料", recipeType("活动"), habitat("特殊"), new RecipeSell(200, 220, 240, 160, 2.4375f), new RecipeRecovery(40, 44, 48, 60), new RecipeItem(findItemByName("海沟海蜇"), 8, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 1, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 3, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(2, "弹力凝胶", recipeType("研制"), habitat("特殊"), new RecipeSell(32, 35, 38, 31, 1.419355f), new RecipeRecovery(6, 7, 7, 9), new RecipeItem(findItemByName("甜味黏土"), 2, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(2, "金阔拉", recipeType("调和"), habitat("特殊"), new RecipeSell(0, 0, 0, 1, 0f), new RecipeRecovery(0, 0, 0, 0), new RecipeItem(findItemByName("黄金小麦"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(2, "丰产宝典", recipeType("秘方"), habitat("火山"), new RecipeSell(990, 1089, 1188, 360, 5.361111f), new RecipeRecovery(198, 217, 237, 297), new RecipeItem(findItemByName("矿盐"), 1, research("少量")), new RecipeItem(findItemByName("蜂蜡"), 4, research("少量")), new RecipeItem(findItemByName("古树花粉"), 1, research("少量")), new RecipeItem(findItemByName("黄金小麦"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(3, "深潜镜", recipeType("秘方"), habitat("湖泊"), new RecipeSell(1132, 1245, 1358, 410, 5.382927f), new RecipeRecovery(226, 249, 271, 339), new RecipeItem(findItemByName("棉雾气团"), 1, research("少量")), new RecipeItem(findItemByName("晶海星"), 5, research("大量")), new RecipeItem(findItemByName("重水"), 1, research("少量")), new RecipeItem(findItemByName("降雨水仙"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(3, "快凝修补液", recipeType("活动"), habitat("特殊"), new RecipeSell(232, 255, 278, 170, 2.658824f), new RecipeRecovery(46, 51, 55, 69), new RecipeItem(findItemByName("增生土块"), 9, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 1, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 1, research("少量")), new RecipeItem(findItemByName("火结晶"), 4, research("少量"))));
        RECIPE_LIST.add(new Recipe(3, "超Q弹果冻", recipeType("研制"), habitat("特殊"), new RecipeSell(72, 79, 86, 70, 1.414286f), new RecipeRecovery(14, 15, 17, 21), new RecipeItem(findItemByName("甜味黏土"), 4, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 5, research("大量"))));
        RECIPE_LIST.add(new Recipe(4, "妖精的魔方", recipeType("秘方"), habitat("湖泊"), new RecipeSell(1252, 1377, 1502, 480, 5.085417f), new RecipeRecovery(250, 275, 300, 375), new RecipeItem(findItemByName("矿石碎片"), 1, research("少量")), new RecipeItem(findItemByName("矿盐"), 2, research("少量")), new RecipeItem(findItemByName("干涸砂砾"), 2, research("少量")), new RecipeItem(findItemByName("厄运蘑菇"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(4, "压缩食物", recipeType("活动"), habitat("特殊"), new RecipeSell(232, 255, 278, 150, 3.013333f), new RecipeRecovery(46, 51, 55, 69), new RecipeItem(findItemByName("海沟海蜇"), 8, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 3, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(4, "番茄酱", recipeType("研制"), habitat("山地"), new RecipeSell(80, 88, 96, 70, 1.757143f), new RecipeRecovery(16, 17, 19, 24), new RecipeItem(findItemByName("甜味黏土"), 8, research("大量")), new RecipeItem(findItemByName("血浆果"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(5, "冰沙", recipeType("研制"), habitat("湖泊"), new RecipeSell(16, 17, 19, 20, 1.05f), new RecipeRecovery(3, 3, 3, 4), new RecipeItem(findItemByName("甜味黏土"), 2, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(5, "沙漠丝绒", recipeType("秘方"), habitat("火山"), new RecipeSell(1260, 1386, 1512, 500, 4.914f), new RecipeRecovery(252, 277, 302, 378), new RecipeItem(findItemByName("彩虹羽翼"), 1, research("少量")), new RecipeItem(findItemByName("棉雾气团"), 2, research("少量")), new RecipeItem(findItemByName("喷射孢子"), 5, research("大量")), new RecipeItem(findItemByName("龙卷斑蝶"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(5, "快愈药膏", recipeType("活动"), habitat("特殊"), new RecipeSell(248, 272, 297, 160, 3.01875f), new RecipeRecovery(49, 54, 59, 74), new RecipeItem(findItemByName("月光石"), 6, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 2, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 3, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(6, "轻灵药", recipeType("研制"), habitat("湖泊"), new RecipeSell(16, 17, 19, 23, 0.956522f), new RecipeRecovery(3, 3, 3, 4), new RecipeItem(findItemByName("魔法冰泉"), 3, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(6, "魔力定标器", recipeType("活动"), habitat("特殊"), new RecipeSell(352, 387, 422, 240, 2.858333f), new RecipeRecovery(70, 77, 84, 105), new RecipeItem(findItemByName("月光石"), 9, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 1, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 4, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(6, "妖精的盲盒", recipeType("秘方"), habitat("草原"), new RecipeSell(1275, 1402, 1530, 470, 5.289362f), new RecipeRecovery(255, 280, 306, 382), new RecipeItem(findItemByName("铜簇"), 1, research("少量")), new RecipeItem(findItemByName("刻金石板"), 1, research("少量")), new RecipeItem(findItemByName("化石鱼骨"), 1, research("少量")), new RecipeItem(findItemByName("幻梦菇"), 5, research("大量"))));
        RECIPE_LIST.add(new Recipe(7, "番茄汤", recipeType("研制"), habitat("湖泊"), new RecipeSell(88, 96, 105, 90, 1.555556f), new RecipeRecovery(17, 19, 21, 26), new RecipeItem(findItemByName("魔法冰泉"), 6, research("大量")), new RecipeItem(findItemByName("血浆果"), 4, research("少量"))));
        RECIPE_LIST.add(new Recipe(7, "帝国绸布", recipeType("秘方"), habitat("草原"), new RecipeSell(1290, 1419, 1548, 480, 5.239583f), new RecipeRecovery(258, 283, 309, 387), new RecipeItem(findItemByName("彩虹羽翼"), 6, research("大量")), new RecipeItem(findItemByName("蜂蜡"), 1, research("少量")), new RecipeItem(findItemByName("古树花粉"), 1, research("少量")), new RecipeItem(findItemByName("降雨水仙"), 5, research("大量"))));
        RECIPE_LIST.add(new Recipe(7, "魔法地图", recipeType("活动"), habitat("特殊"), new RecipeSell(216, 237, 259, 160, 2.63125f), new RecipeRecovery(43, 47, 51, 64), new RecipeItem(findItemByName("家族残徽"), 6, research("大量")), new RecipeItem(findItemByName("火结晶"), 2, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(8, "不老羊皮卷", recipeType("活动"), habitat("特殊"), new RecipeSell(368, 404, 441, 220, 3.259091f), new RecipeRecovery(73, 80, 88, 110), new RecipeItem(findItemByName("家族残徽"), 8, research("大量")), new RecipeItem(findItemByName("火结晶"), 2, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 4, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(8, "碧玉琥珀", recipeType("秘方"), habitat("火山"), new RecipeSell(1297, 1426, 1556, 470, 5.378723f), new RecipeRecovery(259, 285, 311, 389), new RecipeItem(findItemByName("闪亮红砂"), 2, research("少量")), new RecipeItem(findItemByName("铜簇"), 2, research("少量")), new RecipeItem(findItemByName("液态滚石"), 2, research("少量")), new RecipeItem(findItemByName("丛云果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(8, "血腥玛丽", recipeType("研制"), habitat("火山"), new RecipeSell(96, 105, 115, 92, 1.728261f), new RecipeRecovery(19, 21, 23, 28), new RecipeItem(findItemByName("血浆果"), 4, research("少量")), new RecipeItem(findItemByName("坚硬荆棘"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(9, "风情陶罐", recipeType("秘方"), habitat("山地"), new RecipeSell(1335, 1468, 1602, 480, 5.422917f), new RecipeRecovery(267, 293, 320, 400), new RecipeItem(findItemByName("液态滚石"), 1, research("少量")), new RecipeItem(findItemByName("刻金石板"), 1, research("少量")), new RecipeItem(findItemByName("自燃石"), 1, research("少量")), new RecipeItem(findItemByName("炽热蚯蚓"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(9, "混沌理念", recipeType("活动"), habitat("特殊"), new RecipeSell(464, 510, 556, 310, 2.916129f), new RecipeRecovery(92, 102, 111, 139), new RecipeItem(findItemByName("冰髓"), 7, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 3, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 3, research("少量")), new RecipeItem(findItemByName("火结晶"), 3, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(9, "隔热凝胶", recipeType("研制"), habitat("火山"), new RecipeSell(24, 26, 28, 28, 1.142857f), new RecipeRecovery(4, 5, 5, 7), new RecipeItem(findItemByName("甜味黏土"), 2, research("少量")), new RecipeItem(findItemByName("火结晶"), 2, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(10, "面包", recipeType("研制"), habitat("山地"), new RecipeSell(96, 105, 115, 99, 1.585859f), new RecipeRecovery(19, 21, 23, 28), new RecipeItem(findItemByName("甜味黏土"), 2, research("少量")), new RecipeItem(findItemByName("火结晶"), 1, research("少量")), new RecipeItem(findItemByName("黄金小麦"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(10, "飞翔斗篷", recipeType("秘方"), habitat("草原"), new RecipeSell(1477, 1624, 1772, 560, 5.141071f), new RecipeRecovery(295, 324, 354, 443), new RecipeItem(findItemByName("彩虹羽翼"), 7, research("大量")), new RecipeItem(findItemByName("棉雾气团"), 1, research("少量")), new RecipeItem(findItemByName("降雨水仙"), 1, research("少量")), new RecipeItem(findItemByName("龙卷斑蝶"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(10, "坚韧绳索", recipeType("活动"), habitat("特殊"), new RecipeSell(384, 422, 460, 250, 2.992f), new RecipeRecovery(76, 84, 92, 115), new RecipeItem(findItemByName("冰髓"), 6, research("大量")), new RecipeItem(findItemByName("微风粉尘"), 4, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(11, "番茄面包", recipeType("研制"), habitat("山地"), new RecipeSell(104, 114, 124, 92, 1.771739f), new RecipeRecovery(20, 22, 24, 31), new RecipeItem(findItemByName("甜味黏土"), 5, research("大量")), new RecipeItem(findItemByName("火结晶"), 2, research("少量")), new RecipeItem(findItemByName("黄金小麦"), 1, research("少量")), new RecipeItem(findItemByName("血浆果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(11, "地底族工艺品", recipeType("秘方"), habitat("山地"), new RecipeSell(1717, 1888, 2060, 640, 5.229688f), new RecipeRecovery(343, 377, 412, 515), new RecipeItem(findItemByName("重水"), 1, research("少量")), new RecipeItem(findItemByName("自燃石"), 1, research("少量")), new RecipeItem(findItemByName("血浆果"), 5, research("大量")), new RecipeItem(findItemByName("龙卷斑蝶"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(11, "收纳宝石", recipeType("活动"), habitat("特殊"), new RecipeSell(344, 378, 412, 210, 3.190476f), new RecipeRecovery(68, 75, 82, 103), new RecipeItem(findItemByName("不老冰"), 5, research("大量")), new RecipeItem(findItemByName("魔法冰泉"), 2, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 2, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(12, "魔力火苗", recipeType("研制"), habitat("火山"), new RecipeSell(24, 26, 28, 28, 1.142857f), new RecipeRecovery(4, 5, 5, 7), new RecipeItem(findItemByName("火结晶"), 4, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(12, "火山标本", recipeType("秘方"), habitat("山地"), new RecipeSell(2025, 2227, 2430, 770, 5.127273f), new RecipeRecovery(405, 445, 486, 607), new RecipeItem(findItemByName("矿石碎片"), 1, research("少量")), new RecipeItem(findItemByName("火溶虫"), 1, research("少量")), new RecipeItem(findItemByName("岩蛭"), 5, research("大量")), new RecipeItem(findItemByName("干涸地蔓"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(12, "领航罗盘", recipeType("活动"), habitat("特殊"), new RecipeSell(464, 510, 556, 300, 3.013333f), new RecipeRecovery(92, 102, 111, 139), new RecipeItem(findItemByName("不老冰"), 7, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 3, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 4, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 2, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(13, "守夜营帐", recipeType("秘方"), habitat("山地"), new RecipeSell(2114, 2325, 2536, 790, 5.216456f), new RecipeRecovery(422, 465, 507, 634), new RecipeItem(findItemByName("自燃石"), 1, research("少量")), new RecipeItem(findItemByName("喷射孢子"), 5, research("大量")), new RecipeItem(findItemByName("炽热蚯蚓"), 1, research("少量")), new RecipeItem(findItemByName("辛辣辣椒"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(13, "冰霜蘑菇", recipeType("研制"), habitat("湖泊"), new RecipeSell(10, 11, 12, 15, 1f), new RecipeRecovery(2, 2, 2, 3), new RecipeItem(findItemByName("魔法冰泉"), 1, research("少量")), new RecipeItem(findItemByName("喷射孢子"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(13, "冰洁之心", recipeType("活动"), habitat("特殊"), new RecipeSell(384, 422, 460, 238, 3.142857f), new RecipeRecovery(76, 84, 92, 115), new RecipeItem(findItemByName("魔动环"), 6, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 2, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 3, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(14, "登云梯", recipeType("活动"), habitat("特殊"), new RecipeSell(499, 548, 598, 310, 3.135484f), new RecipeRecovery(99, 109, 119, 149), new RecipeItem(findItemByName("魔动环"), 6, research("大量")), new RecipeItem(findItemByName("微风粉尘"), 4, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(14, "学徒纹章", recipeType("秘方"), habitat("火山"), new RecipeSell(2149, 2363, 2578, 840, 4.986905f), new RecipeRecovery(429, 472, 515, 644), new RecipeItem(findItemByName("铜簇"), 1, research("少量")), new RecipeItem(findItemByName("刻金石板"), 1, research("少量")), new RecipeItem(findItemByName("厄运蘑菇"), 1, research("少量")), new RecipeItem(findItemByName("星辰珊瑚"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(14, "燃火蘑菇", recipeType("研制"), habitat("火山"), new RecipeSell(24, 26, 28, 30, 1.133333f), new RecipeRecovery(4, 5, 5, 7), new RecipeItem(findItemByName("火结晶"), 2, research("少量")), new RecipeItem(findItemByName("喷射孢子"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(15, "林木之心", recipeType("活动"), habitat("特殊"), new RecipeSell(416, 457, 499, 310, 2.616129f), new RecipeRecovery(83, 91, 99, 124), new RecipeItem(findItemByName("魔魂残片"), 9, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 1, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 4, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(15, "狼牙冰雕", recipeType("秘方"), habitat("湖泊"), new RecipeSell(2226, 2448, 2671, 820, 5.292683f), new RecipeRecovery(445, 489, 534, 667), new RecipeItem(findItemByName("晶海星"), 1, research("少量")), new RecipeItem(findItemByName("重水"), 1, research("少量")), new RecipeItem(findItemByName("星辰珊瑚"), 1, research("少量")), new RecipeItem(findItemByName("岩蛭"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(15, "玛丽的恶作剧", recipeType("研制"), habitat("特殊"), new RecipeSell(96, 105, 115, 87, 1.804598f), new RecipeRecovery(19, 21, 23, 28), new RecipeItem(findItemByName("血浆果"), 3, research("少量")), new RecipeItem(findItemByName("喷射孢子"), 1, research("少量")), new RecipeItem(findItemByName("坚硬荆棘"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(16, "魔力蒸汽", recipeType("研制"), habitat("湖泊"), new RecipeSell(24, 26, 28, 25, 1.24f), new RecipeRecovery(4, 5, 5, 7), new RecipeItem(findItemByName("魔法冰泉"), 3, research("少量")), new RecipeItem(findItemByName("火结晶"), 1, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(16, "港湾珍珠", recipeType("秘方"), habitat("湖泊"), new RecipeSell(2338, 2571, 2805, 850, 5.362353f), new RecipeRecovery(467, 514, 561, 701), new RecipeItem(findItemByName("重水"), 1, research("少量")), new RecipeItem(findItemByName("自燃石"), 1, research("少量")), new RecipeItem(findItemByName("黄金小麦"), 5, research("大量")), new RecipeItem(findItemByName("火溶虫"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(16, "魔法能晶", recipeType("活动"), habitat("特殊"), new RecipeSell(384, 422, 460, 238, 3.142857f), new RecipeRecovery(76, 84, 92, 115), new RecipeItem(findItemByName("魔魂残片"), 5, research("大量")), new RecipeItem(findItemByName("魔法冰泉"), 2, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 2, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(17, "熔火核心", recipeType("秘方"), habitat("火山"), new RecipeSell(2779, 3056, 3334, 1060, 5.111321f), new RecipeRecovery(555, 611, 666, 833), new RecipeItem(findItemByName("液态滚石"), 1, research("少量")), new RecipeItem(findItemByName("自燃石"), 1, research("少量")), new RecipeItem(findItemByName("火溶虫"), 1, research("少量")), new RecipeItem(findItemByName("辛辣辣椒"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(17, "灰烬", recipeType("研制"), habitat("山地"), new RecipeSell(24, 26, 28, 30, 1.033333f), new RecipeRecovery(4, 5, 5, 7), new RecipeItem(findItemByName("火结晶"), 3, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(17, "魔神像", recipeType("活动"), habitat("特殊"), new RecipeSell(499, 548, 598, 310, 3.135484f), new RecipeRecovery(99, 109, 119, 149), new RecipeItem(findItemByName("魔魂残片"), 7, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 3, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 4, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 2, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(18, "自然精华", recipeType("研制"), habitat("草原"), new RecipeSell(24, 26, 28, 28, 1.142857f), new RecipeRecovery(4, 5, 5, 7), new RecipeItem(findItemByName("微风粉尘"), 4, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(18, "驱兽香", recipeType("活动"), habitat("特殊"), new RecipeSell(416, 457, 499, 310, 2.616129f), new RecipeRecovery(83, 91, 99, 124), new RecipeItem(findItemByName("魔动环"), 8, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 3, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(18, "狮子之眼", recipeType("秘方"), habitat("草原"), new RecipeSell(2842, 3126, 3410, 900, 6.156667f), new RecipeRecovery(568, 625, 682, 852), new RecipeItem(findItemByName("彩虹羽翼"), 5, research("大量")), new RecipeItem(findItemByName("晶海星"), 4, research("少量")), new RecipeItem(findItemByName("自燃石"), 1, research("少量")), new RecipeItem(findItemByName("黄金小麦"), 5, research("大量")), new RecipeItem(findItemByName("折光兰"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(19, "危机香精", recipeType("活动"), habitat("特殊"), new RecipeSell(384, 422, 460, 238, 3.142857f), new RecipeRecovery(76, 84, 92, 115), new RecipeItem(findItemByName("生命枝杈"), 7, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 4, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(19, "万年祖木雕刻", recipeType("秘方"), habitat("草原"), new RecipeSell(2947, 3241, 3536, 1110, 5.176577f), new RecipeRecovery(589, 648, 707, 884), new RecipeItem(findItemByName("彩虹羽翼"), 5, research("大量")), new RecipeItem(findItemByName("古树花粉"), 1, research("少量")), new RecipeItem(findItemByName("铜簇"), 1, research("少量")), new RecipeItem(findItemByName("刻金石板"), 1, research("少量")), new RecipeItem(findItemByName("星辰珊瑚"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(19, "红色墨水", recipeType("研制"), habitat("湖泊"), new RecipeSell(80, 88, 96, 70, 1.671429f), new RecipeRecovery(16, 17, 19, 24), new RecipeItem(findItemByName("魔法冰泉"), 8, research("大量")), new RecipeItem(findItemByName("矿盐"), 2, research("少量")), new RecipeItem(findItemByName("血浆果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(20, "雪雾", recipeType("活动"), habitat("特殊"), new RecipeSell(499, 548, 598, 310, 3.135484f), new RecipeRecovery(99, 109, 119, 149), new RecipeItem(findItemByName("生命枝杈"), 7, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 3, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 3, research("少量")), new RecipeItem(findItemByName("火结晶"), 3, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(20, "万兽的赠予", recipeType("秘方"), habitat("山地"), new RecipeSell(2975, 3272, 3570, 1190, 4.87479f), new RecipeRecovery(595, 654, 714, 892), new RecipeItem(findItemByName("蜂蜡"), 6, research("大量")), new RecipeItem(findItemByName("深谷坚石"), 2, research("少量")), new RecipeItem(findItemByName("血浆果"), 2, research("少量")), new RecipeItem(findItemByName("岩蛭"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(20, "营养燕麦", recipeType("研制"), habitat("湖泊"), new RecipeSell(384, 422, 460, 257, 2.894942f), new RecipeRecovery(76, 84, 92, 115), new RecipeItem(findItemByName("魔法冰泉"), 7, research("大量")), new RecipeItem(findItemByName("黄金小麦"), 1, research("少量")), new RecipeItem(findItemByName("丛云果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(21, "猎人陷阱", recipeType("研制"), habitat("山地"), new RecipeSell(96, 105, 115, 82, 1.878049f), new RecipeRecovery(19, 21, 23, 28), new RecipeItem(findItemByName("坚硬的喙"), 1, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 5, research("大量")), new RecipeItem(findItemByName("坚硬荆棘"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(21, "天选桂冠", recipeType("秘方"), habitat("山地"), new RecipeSell(3290, 3619, 3948, 1210, 5.301653f), new RecipeRecovery(658, 723, 789, 987), new RecipeItem(findItemByName("彩虹羽翼"), 5, research("大量")), new RecipeItem(findItemByName("晶海星"), 1, research("少量")), new RecipeItem(findItemByName("刻金石板"), 1, research("少量")), new RecipeItem(findItemByName("星辰珊瑚"), 1, research("少量")), new RecipeItem(findItemByName("丛云果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(21, "引路灯", recipeType("活动"), habitat("特殊"), new RecipeSell(416, 457, 499, 310, 2.616129f), new RecipeRecovery(83, 91, 99, 124), new RecipeItem(findItemByName("衍生晶壤"), 8, research("大量")), new RecipeItem(findItemByName("火结晶"), 2, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 4, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(22, "拐杖", recipeType("研制"), habitat("山地"), new RecipeSell(88, 96, 105, 92, 1.467391f), new RecipeRecovery(17, 19, 21, 26), new RecipeItem(findItemByName("坚硬的喙"), 6, research("大量")), new RecipeItem(findItemByName("坚硬荆棘"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(22, "冬火", recipeType("秘方"), habitat("火山"), new RecipeSell(3423, 3765, 4107, 1240, 5.382258f), new RecipeRecovery(684, 753, 821, 1026), new RecipeItem(findItemByName("矿盐"), 1, research("少量")), new RecipeItem(findItemByName("重水"), 5, research("大量")), new RecipeItem(findItemByName("自燃石"), 1, research("少量")), new RecipeItem(findItemByName("辛辣辣椒"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(22, "再生木材", recipeType("活动"), habitat("特殊"), new RecipeSell(384, 422, 460, 238, 3.142857f), new RecipeRecovery(76, 84, 92, 115), new RecipeItem(findItemByName("衍生晶壤"), 8, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 1, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 3, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(23, "可动魔偶", recipeType("秘方"), habitat("湖泊"), new RecipeSell(3529, 3881, 4234, 1410, 4.879433f), new RecipeRecovery(705, 776, 846, 1058), new RecipeItem(findItemByName("彩虹羽翼"), 8, research("大量")), new RecipeItem(findItemByName("妖精粉尘"), 1, research("少量")), new RecipeItem(findItemByName("重水"), 1, research("少量")), new RecipeItem(findItemByName("血浆果"), 5, research("大量")), new RecipeItem(findItemByName("星辰珊瑚"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(23, "云雨精华", recipeType("研制"), habitat("湖泊"), new RecipeSell(424, 466, 508, 265, 3.079245f), new RecipeRecovery(84, 93, 101, 127), new RecipeItem(findItemByName("魔法冰泉"), 5, research("大量")), new RecipeItem(findItemByName("降雨水仙"), 2, research("少量")), new RecipeItem(findItemByName("丛云果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(23, "再生石材", recipeType("活动"), habitat("特殊"), new RecipeSell(499, 548, 598, 310, 3.135484f), new RecipeRecovery(99, 109, 119, 149), new RecipeItem(findItemByName("衍生晶壤"), 6, research("大量")), new RecipeItem(findItemByName("火结晶"), 2, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(24, "回魔药粉", recipeType("研制"), habitat("草原"), new RecipeSell(120, 132, 144, 100, 1.86f), new RecipeRecovery(24, 26, 28, 36), new RecipeItem(findItemByName("微风粉尘"), 6, research("大量")), new RecipeItem(findItemByName("坚硬的喙"), 1, research("少量")), new RecipeItem(findItemByName("降雨水仙"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(24, "阻魔环", recipeType("活动"), habitat("特殊"), new RecipeSell(416, 457, 499, 310, 2.616129f), new RecipeRecovery(83, 91, 99, 124), new RecipeItem(findItemByName("衍生晶壤"), 9, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 1, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 1, research("少量")), new RecipeItem(findItemByName("火结晶"), 4, research("少量"))));
        RECIPE_LIST.add(new Recipe(24, "帝王橄榄油", recipeType("秘方"), habitat("火山"), new RecipeSell(3562, 3918, 4274, 1310, 5.301527f), new RecipeRecovery(712, 783, 854, 1068), new RecipeItem(findItemByName("蜂蜡"), 5, research("大量")), new RecipeItem(findItemByName("古树花粉"), 5, research("大量")), new RecipeItem(findItemByName("妖精粉尘"), 1, research("少量")), new RecipeItem(findItemByName("幻梦菇"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(25, "薄风衣", recipeType("活动"), habitat("特殊"), new RecipeSell(416, 457, 499, 310, 2.616129f), new RecipeRecovery(83, 91, 99, 124), new RecipeItem(findItemByName("爆炸甲壳"), 6, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 2, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 3, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(25, "降雨云朵", recipeType("研制"), habitat("草原"), new RecipeSell(472, 519, 566, 295, 3.084746f), new RecipeRecovery(94, 103, 113, 141), new RecipeItem(findItemByName("微风粉尘"), 5, research("大量")), new RecipeItem(findItemByName("降雨水仙"), 3, research("少量")), new RecipeItem(findItemByName("丛云果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(25, "野地藏", recipeType("秘方"), habitat("草原"), new RecipeSell(3685, 4053, 4422, 1390, 5.169065f), new RecipeRecovery(737, 810, 884, 1105), new RecipeItem(findItemByName("重水"), 3, research("少量")), new RecipeItem(findItemByName("深谷坚石"), 2, research("少量")), new RecipeItem(findItemByName("幻梦菇"), 5, research("大量")), new RecipeItem(findItemByName("厄运蘑菇"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(26, "精盐", recipeType("研制"), habitat("湖泊"), new RecipeSell(88, 96, 105, 90, 1.466667f), new RecipeRecovery(17, 19, 21, 26), new RecipeItem(findItemByName("矿盐"), 7, research("大量")), new RecipeItem(findItemByName("岩蛭"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(26, "便捷快艇", recipeType("活动"), habitat("特殊"), new RecipeSell(384, 422, 460, 238, 3.142857f), new RecipeRecovery(76, 84, 92, 115), new RecipeItem(findItemByName("怪力药草"), 6, research("大量")), new RecipeItem(findItemByName("微风粉尘"), 4, research("少量")), new RecipeItem(findItemByName("黄金小麦"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(26, "拱门石雕", recipeType("秘方"), habitat("山地"), new RecipeSell(3744, 4118, 4492, 1440, 5.069444f), new RecipeRecovery(748, 823, 898, 1123), new RecipeItem(findItemByName("刻金石板"), 2, research("少量")), new RecipeItem(findItemByName("自燃石"), 5, research("大量")), new RecipeItem(findItemByName("深谷坚石"), 1, research("少量")), new RecipeItem(findItemByName("岩蛭"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(27, "导虫", recipeType("活动"), habitat("特殊"), new RecipeSell(499, 548, 598, 310, 3.135484f), new RecipeRecovery(99, 109, 119, 149), new RecipeItem(findItemByName("凝神圣水"), 9, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 1, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 4, research("少量")), new RecipeItem(findItemByName("黄金小麦"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(27, "尤元素", recipeType("秘方"), habitat("火山"), new RecipeSell(3815, 4196, 4578, 1520, 4.894079f), new RecipeRecovery(763, 839, 915, 1144), new RecipeItem(findItemByName("闪亮红砂"), 2, research("少量")), new RecipeItem(findItemByName("晶海星"), 5, research("大量")), new RecipeItem(findItemByName("妖精粉尘"), 2, research("少量")), new RecipeItem(findItemByName("幻梦菇"), 5, research("大量")), new RecipeItem(findItemByName("火溶虫"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(27, "清洗剂", recipeType("研制"), habitat("火山"), new RecipeSell(440, 484, 528, 348, 2.287356f), new RecipeRecovery(88, 96, 105, 132), new RecipeItem(findItemByName("矿盐"), 1, research("少量")), new RecipeItem(findItemByName("折光兰"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(28, "冒险者手礼", recipeType("秘方"), habitat("草原"), new RecipeSell(3945, 4339, 4734, 1460, 5.268493f), new RecipeRecovery(789, 867, 946, 1183), new RecipeItem(findItemByName("铜簇"), 4, research("少量")), new RecipeItem(findItemByName("妖精粉尘"), 2, research("少量")), new RecipeItem(findItemByName("深谷坚石"), 1, research("少量")), new RecipeItem(findItemByName("血浆果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(28, "功能泉水", recipeType("活动"), habitat("特殊"), new RecipeSell(416, 457, 499, 310, 2.616129f), new RecipeRecovery(83, 91, 99, 124), new RecipeItem(findItemByName("膨胀木"), 5, research("大量")), new RecipeItem(findItemByName("魔法冰泉"), 2, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 2, research("少量")), new RecipeItem(findItemByName("黄金小麦"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(28, "折光蘑菇", recipeType("研制"), habitat("草原"), new RecipeSell(440, 484, 528, 348, 2.295977f), new RecipeRecovery(88, 96, 105, 132), new RecipeItem(findItemByName("折光兰"), 1, research("少量")), new RecipeItem(findItemByName("喷射孢子"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(29, "山地蚨蛉壳", recipeType("秘方"), habitat("湖泊"), new RecipeSell(4296, 4725, 5155, 1560, 5.369872f), new RecipeRecovery(859, 945, 1031, 1288), new RecipeItem(findItemByName("矿石碎片"), 8, research("大量")), new RecipeItem(findItemByName("蜂蜡"), 2, research("少量")), new RecipeItem(findItemByName("妖精粉尘"), 3, research("少量")), new RecipeItem(findItemByName("岩蛭"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(29, "易燃粉", recipeType("研制"), habitat("火山"), new RecipeSell(104, 114, 124, 100, 1.5f), new RecipeRecovery(20, 22, 24, 31), new RecipeItem(findItemByName("火结晶"), 4, research("少量")), new RecipeItem(findItemByName("闪亮红砂"), 4, research("少量")), new RecipeItem(findItemByName("坚硬的喙"), 4, research("少量"))));
        RECIPE_LIST.add(new Recipe(29, "规测尺", recipeType("活动"), habitat("特殊"), new RecipeSell(384, 422, 460, 238, 3.142857f), new RecipeRecovery(76, 84, 92, 115), new RecipeItem(findItemByName("缩小宝石"), 7, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 3, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 4, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 2, research("少量")), new RecipeItem(findItemByName("黄金小麦"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(30, "喝彩飘带", recipeType("活动"), habitat("特殊"), new RecipeSell(499, 548, 598, 310, 3.135484f), new RecipeRecovery(99, 109, 119, 149), new RecipeItem(findItemByName("无风蛛网"), 8, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 3, research("少量")), new RecipeItem(findItemByName("黄金小麦"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(30, "提纯火元素", recipeType("研制"), habitat("火山"), new RecipeSell(104, 114, 124, 100, 1.62f), new RecipeRecovery(20, 22, 24, 31), new RecipeItem(findItemByName("火结晶"), 2, research("少量")), new RecipeItem(findItemByName("闪亮红砂"), 3, research("少量")), new RecipeItem(findItemByName("岩蛭"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(30, "智慧枝干", recipeType("秘方"), habitat("草原"), new RecipeSell(4329, 4761, 5194, 1630, 5.177914f), new RecipeRecovery(865, 952, 1038, 1298), new RecipeItem(findItemByName("古树花粉"), 2, research("少量")), new RecipeItem(findItemByName("妖精粉尘"), 1, research("少量")), new RecipeItem(findItemByName("深谷坚石"), 1, research("少量")), new RecipeItem(findItemByName("折光兰"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(31, "蜡烛", recipeType("研制"), habitat("火山"), new RecipeSell(224, 246, 268, 169, 2.094675f), new RecipeRecovery(44, 49, 53, 67), new RecipeItem(findItemByName("火结晶"), 5, research("大量")), new RecipeItem(findItemByName("闪亮红砂"), 4, research("少量")), new RecipeItem(findItemByName("蜂蜡"), 4, research("少量"))));
        RECIPE_LIST.add(new Recipe(31, "花束喇叭", recipeType("活动"), habitat("特殊"), new RecipeSell(416, 457, 499, 310, 2.616129f), new RecipeRecovery(83, 91, 99, 124), new RecipeItem(findItemByName("怪力药草"), 7, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 4, research("少量")), new RecipeItem(findItemByName("折光兰"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(31, "铭文石碑", recipeType("秘方"), habitat("湖泊"), new RecipeSell(2700, 2970, 3240, 1000, 5.265f), new RecipeRecovery(540, 594, 648, 810), new RecipeItem(findItemByName("矿石碎片"), 5, research("大量")), new RecipeItem(findItemByName("刻金石板"), 4, research("少量")), new RecipeItem(findItemByName("深谷坚石"), 1, research("少量")), new RecipeItem(findItemByName("星辰珊瑚"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(32, "抛光粉", recipeType("研制"), habitat("火山"), new RecipeSell(496, 545, 595, 348, 2.54023f), new RecipeRecovery(99, 109, 119, 148), new RecipeItem(findItemByName("闪亮红砂"), 1, research("少量")), new RecipeItem(findItemByName("珍珠果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(32, "快速再生骨粉", recipeType("活动"), habitat("特殊"), new RecipeSell(416, 457, 499, 310, 2.616129f), new RecipeRecovery(83, 91, 99, 124), new RecipeItem(findItemByName("爆炸甲壳"), 7, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 3, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 3, research("少量")), new RecipeItem(findItemByName("火结晶"), 3, research("少量")), new RecipeItem(findItemByName("折光兰"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(32, "雾霭之叶", recipeType("秘方"), habitat("湖泊"), new RecipeSell(4563, 5019, 5475, 1780, 4.998315f), new RecipeRecovery(912, 1003, 1095, 1368), new RecipeItem(findItemByName("棉雾气团"), 4, research("少量")), new RecipeItem(findItemByName("重水"), 1, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 5, research("大量")), new RecipeItem(findItemByName("黑海带"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(33, "信号弹", recipeType("活动"), habitat("特殊"), new RecipeSell(384, 422, 460, 238, 3.142857f), new RecipeRecovery(76, 84, 92, 115), new RecipeItem(findItemByName("缩小宝石"), 8, research("大量")), new RecipeItem(findItemByName("火结晶"), 2, research("少量")), new RecipeItem(findItemByName("微风粉尘"), 4, research("少量")), new RecipeItem(findItemByName("折光兰"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(33, "透视镜", recipeType("秘方"), habitat("湖泊"), new RecipeSell(4582, 5040, 5498, 1660, 5.381928f), new RecipeRecovery(916, 1008, 1099, 1374), new RecipeItem(findItemByName("古树花粉"), 1, research("少量")), new RecipeItem(findItemByName("妖精粉尘"), 1, research("少量")), new RecipeItem(findItemByName("深谷坚石"), 2, research("少量")), new RecipeItem(findItemByName("折光兰"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(33, "昏睡面包", recipeType("研制"), habitat("山地"), new RecipeSell(96, 105, 115, 97, 1.57732f), new RecipeRecovery(19, 21, 23, 28), new RecipeItem(findItemByName("甜味黏土"), 5, research("大量")), new RecipeItem(findItemByName("火结晶"), 2, research("少量")), new RecipeItem(findItemByName("黄金小麦"), 1, research("少量")), new RecipeItem(findItemByName("幻梦菇"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(34, "猎人的护身符", recipeType("秘方"), habitat("草原"), new RecipeSell(4719, 5190, 5662, 1780, 5.169101f), new RecipeRecovery(943, 1038, 1132, 1415), new RecipeItem(findItemByName("彩虹羽翼"), 3, research("少量")), new RecipeItem(findItemByName("液态滚石"), 3, research("少量")), new RecipeItem(findItemByName("深谷坚石"), 3, research("少量")), new RecipeItem(findItemByName("厄运蘑菇"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(34, "昏睡药粉", recipeType("研制"), habitat("草原"), new RecipeSell(96, 105, 115, 95, 1.642105f), new RecipeRecovery(19, 21, 23, 28), new RecipeItem(findItemByName("微风粉尘"), 1, research("少量")), new RecipeItem(findItemByName("坚硬的喙"), 1, research("少量")), new RecipeItem(findItemByName("幻梦菇"), 4, research("少量"))));
        RECIPE_LIST.add(new Recipe(34, "行军营帐", recipeType("活动"), habitat("特殊"), new RecipeSell(499, 548, 598, 310, 3.135484f), new RecipeRecovery(99, 109, 119, 149), new RecipeItem(findItemByName("无风蛛网"), 8, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 1, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 3, research("少量")), new RecipeItem(findItemByName("折光兰"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(35, "袖珍农舍", recipeType("活动"), habitat("特殊"), new RecipeSell(416, 457, 499, 310, 2.616129f), new RecipeRecovery(83, 91, 99, 124), new RecipeItem(findItemByName("无风蛛网"), 6, research("大量")), new RecipeItem(findItemByName("火结晶"), 2, research("少量")), new RecipeItem(findItemByName("折光兰"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(35, "顶级麦酒", recipeType("研制"), habitat("草原"), new RecipeSell(104, 114, 124, 102, 1.676471f), new RecipeRecovery(20, 22, 24, 31), new RecipeItem(findItemByName("黄金小麦"), 1, research("少量")), new RecipeItem(findItemByName("幻梦菇"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(35, "气象球", recipeType("秘方"), habitat("草原"), new RecipeSell(2670, 2937, 3204, 950, 5.48f), new RecipeRecovery(534, 587, 640, 801), new RecipeItem(findItemByName("蜂蜡"), 4, research("少量")), new RecipeItem(findItemByName("古树花粉"), 1, research("少量")), new RecipeItem(findItemByName("丛云果"), 1, research("少量")), new RecipeItem(findItemByName("风滚草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(36, "引火器", recipeType("活动"), habitat("特殊"), new RecipeSell(384, 422, 460, 238, 3.142857f), new RecipeRecovery(76, 84, 92, 115), new RecipeItem(findItemByName("爆炸甲壳"), 9, research("大量")), new RecipeItem(findItemByName("甜味黏土"), 1, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 1, research("少量")), new RecipeItem(findItemByName("折光兰"), 4, research("少量"))));
        RECIPE_LIST.add(new Recipe(36, "节日烟花", recipeType("研制"), habitat("火山"), new RecipeSell(88, 96, 105, 81, 1.654321f), new RecipeRecovery(17, 19, 21, 26), new RecipeItem(findItemByName("火结晶"), 3, research("少量")), new RecipeItem(findItemByName("彩虹羽翼"), 3, research("少量")), new RecipeItem(findItemByName("喷射孢子"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(36, "雪原机动装置", recipeType("秘方"), habitat("火山"), new RecipeSell(5323, 5855, 6387, 1700, 6.105294f), new RecipeRecovery(1064, 1171, 1277, 1596), new RecipeItem(findItemByName("矿石碎片"), 2, research("少量")), new RecipeItem(findItemByName("铜簇"), 4, research("少量")), new RecipeItem(findItemByName("液态滚石"), 1, research("少量")), new RecipeItem(findItemByName("刻金石板"), 1, research("少量")), new RecipeItem(findItemByName("深谷坚石"), 4, research("少量"))));
        RECIPE_LIST.add(new Recipe(37, "精致红宝石", recipeType("研制"), habitat("山地"), new RecipeSell(128, 140, 153, 100, 1.85f), new RecipeRecovery(25, 28, 30, 38), new RecipeItem(findItemByName("矿石碎片"), 5, research("大量")), new RecipeItem(findItemByName("闪亮红砂"), 5, research("大量"))));
        RECIPE_LIST.add(new Recipe(37, "永夜花", recipeType("秘方"), habitat("山地"), new RecipeSell(2954, 3249, 3544, 1050, 5.484762f), new RecipeRecovery(590, 649, 708, 886), new RecipeItem(findItemByName("棉雾气团"), 1, research("少量")), new RecipeItem(findItemByName("晶海星"), 2, research("少量")), new RecipeItem(findItemByName("折光兰"), 1, research("少量")), new RecipeItem(findItemByName("黑海带"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(38, "黑色通行证", recipeType("秘方"), habitat("山地"), new RecipeSell(5596, 6155, 6715, 1800, 6.062222f), new RecipeRecovery(1119, 1231, 1343, 1678), new RecipeItem(findItemByName("蜂蜡"), 6, research("大量")), new RecipeItem(findItemByName("铜簇"), 2, research("少量")), new RecipeItem(findItemByName("黑海带"), 1, research("少量")), new RecipeItem(findItemByName("丛云果"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(38, "云果虫", recipeType("研制"), habitat("火山"), new RecipeSell(512, 563, 614, 360, 2.825f), new RecipeRecovery(102, 112, 122, 153), new RecipeItem(findItemByName("炽热蚯蚓"), 1, research("少量")), new RecipeItem(findItemByName("丛云果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(39, "蜜汁面包", recipeType("研制"), habitat("山地"), new RecipeSell(280, 308, 336, 198, 2.479798f), new RecipeRecovery(56, 61, 67, 84), new RecipeItem(findItemByName("甜味黏土"), 1, research("少量")), new RecipeItem(findItemByName("火结晶"), 1, research("少量")), new RecipeItem(findItemByName("蜂蜡"), 1, research("少量")), new RecipeItem(findItemByName("黄金小麦"), 1, research("少量")), new RecipeItem(findItemByName("蜜虫"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(39, "沙漠之风", recipeType("秘方"), habitat("湖泊"), new RecipeSell(4860, 5346, 5832, 1620, 5.85f), new RecipeRecovery(972, 1069, 1166, 1458), new RecipeItem(findItemByName("古树花粉"), 2, research("少量")), new RecipeItem(findItemByName("妖精粉尘"), 1, research("少量")), new RecipeItem(findItemByName("炽热蚯蚓"), 1, research("少量")), new RecipeItem(findItemByName("火溶虫"), 1, research("少量")), new RecipeItem(findItemByName("风滚草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(40, "蜜饯", recipeType("研制"), habitat("草原"), new RecipeSell(240, 264, 288, 188, 2.271277f), new RecipeRecovery(48, 52, 57, 72), new RecipeItem(findItemByName("蜂蜡"), 1, research("少量")), new RecipeItem(findItemByName("黄金小麦"), 1, research("少量")), new RecipeItem(findItemByName("蜜虫"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(40, "狮子石雕", recipeType("秘方"), habitat("山地"), new RecipeSell(2580, 2838, 3096, 950, 5.295789f), new RecipeRecovery(516, 567, 619, 774), new RecipeItem(findItemByName("铜簇"), 1, research("少量")), new RecipeItem(findItemByName("深谷坚石"), 1, research("少量")), new RecipeItem(findItemByName("炽热蚯蚓"), 1, research("少量")), new RecipeItem(findItemByName("火溶虫"), 5, research("大量"))));
        RECIPE_LIST.add(new Recipe(41, "蜜酱", recipeType("研制"), habitat("草原"), new RecipeSell(112, 123, 134, 86, 2.27907f), new RecipeRecovery(22, 24, 26, 33), new RecipeItem(findItemByName("蜂蜡"), 1, research("少量")), new RecipeItem(findItemByName("蜜虫"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(42, "甜蜜麦粉", recipeType("研制"), habitat("山地"), new RecipeSell(272, 299, 326, 204, 2.406863f), new RecipeRecovery(54, 59, 65, 81), new RecipeItem(findItemByName("黄金小麦"), 2, research("少量")), new RecipeItem(findItemByName("蜜虫"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(43, "微光药粉", recipeType("研制"), habitat("草原"), new RecipeSell(232, 255, 278, 185, 2.12973f), new RecipeRecovery(46, 51, 55, 69), new RecipeItem(findItemByName("微风粉尘"), 7, research("大量")), new RecipeItem(findItemByName("坚硬的喙"), 6, research("大量")), new RecipeItem(findItemByName("长明草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(44, "营火", recipeType("研制"), habitat("山地"), new RecipeSell(256, 281, 307, 194, 2.329897f), new RecipeRecovery(51, 56, 61, 76), new RecipeItem(findItemByName("矿石碎片"), 4, research("少量")), new RecipeItem(findItemByName("坚硬荆棘"), 2, research("少量")), new RecipeItem(findItemByName("长明草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(45, "荧光粉", recipeType("研制"), habitat("草原"), new RecipeSell(592, 651, 710, 438, 2.424658f), new RecipeRecovery(118, 130, 142, 177), new RecipeItem(findItemByName("坚硬的喙"), 1, research("少量")), new RecipeItem(findItemByName("折光兰"), 1, research("少量")), new RecipeItem(findItemByName("长明草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(46, "光亮魔杖", recipeType("研制"), habitat("火山"), new RecipeSell(248, 272, 297, 212, 2.150943f), new RecipeRecovery(49, 54, 59, 74), new RecipeItem(findItemByName("坚硬荆棘"), 1, research("少量")), new RecipeItem(findItemByName("长明草"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(47, "七彩棉花", recipeType("研制"), habitat("草原"), new RecipeSell(240, 264, 288, 177, 2.135593f), new RecipeRecovery(48, 52, 57, 72), new RecipeItem(findItemByName("彩虹羽翼"), 6, research("大量")), new RecipeItem(findItemByName("棉雾气团"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(48, "异域绒布", recipeType("研制"), habitat("草原"), new RecipeSell(256, 281, 307, 190, 2.2f), new RecipeRecovery(51, 56, 61, 76), new RecipeItem(findItemByName("彩虹羽翼"), 6, research("大量")), new RecipeItem(findItemByName("棉雾气团"), 2, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 6, research("大量"))));
        RECIPE_LIST.add(new Recipe(49, "翼根果", recipeType("研制"), habitat("草原"), new RecipeSell(320, 352, 384, 227, 2.726872f), new RecipeRecovery(64, 70, 76, 96), new RecipeItem(findItemByName("彩虹羽翼"), 1, research("少量")), new RecipeItem(findItemByName("棉雾气团"), 1, research("少量")), new RecipeItem(findItemByName("丛云果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(50, "钓鱼竿", recipeType("研制"), habitat("火山"), new RecipeSell(192, 211, 230, 153, 2.078431f), new RecipeRecovery(38, 42, 46, 57), new RecipeItem(findItemByName("棉雾气团"), 3, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 2, research("少量")), new RecipeItem(findItemByName("坚硬荆棘"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(51, "美梦香薰", recipeType("研制"), habitat("湖泊"), new RecipeSell(528, 580, 633, 393, 2.394402f), new RecipeRecovery(105, 116, 126, 158), new RecipeItem(findItemByName("棉雾气团"), 1, research("少量")), new RecipeItem(findItemByName("折光兰"), 1, research("少量")), new RecipeItem(findItemByName("幻梦菇"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(52, "植物催生云", recipeType("研制"), habitat("山地"), new RecipeSell(136, 149, 163, 110, 2.072727f), new RecipeRecovery(27, 29, 32, 40), new RecipeItem(findItemByName("棉雾气团"), 2, research("少量")), new RecipeItem(findItemByName("喷射孢子"), 1, research("少量")), new RecipeItem(findItemByName("降雨水仙"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(53, "迷幻香薰", recipeType("研制"), habitat("草原"), new RecipeSell(232, 255, 278, 165, 2.333333f), new RecipeRecovery(46, 51, 55, 69), new RecipeItem(findItemByName("棉雾气团"), 3, research("少量")), new RecipeItem(findItemByName("幻梦菇"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(54, "蓝调香薰", recipeType("研制"), habitat("草原"), new RecipeSell(192, 211, 230, 155, 2.058065f), new RecipeRecovery(38, 42, 46, 57), new RecipeItem(findItemByName("棉雾气团"), 3, research("少量")), new RecipeItem(findItemByName("幻梦菇"), 1, research("少量")), new RecipeItem(findItemByName("降雨水仙"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(55, "厄运药粉", recipeType("研制"), habitat("草原"), new RecipeSell(288, 316, 345, 200, 2.49f), new RecipeRecovery(57, 63, 69, 86), new RecipeItem(findItemByName("微风粉尘"), 4, research("少量")), new RecipeItem(findItemByName("坚硬的喙"), 3, research("少量")), new RecipeItem(findItemByName("厄运蘑菇"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(56, "厄运香薰", recipeType("研制"), habitat("草原"), new RecipeSell(264, 290, 316, 195, 2.266667f), new RecipeRecovery(52, 58, 63, 79), new RecipeItem(findItemByName("棉雾气团"), 3, research("少量")), new RecipeItem(findItemByName("幻梦菇"), 2, research("少量")), new RecipeItem(findItemByName("厄运蘑菇"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(57, "珍珠粉", recipeType("研制"), habitat("湖泊"), new RecipeSell(1380, 1518, 1656, 840, 3.369048f), new RecipeRecovery(276, 303, 331, 414), new RecipeItem(findItemByName("甲贝"), 8, research("大量")), new RecipeItem(findItemByName("珍珠果"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(58, "黑色墨水", recipeType("研制"), habitat("湖泊"), new RecipeSell(120, 132, 144, 120, 1.458333f), new RecipeRecovery(24, 26, 28, 36), new RecipeItem(findItemByName("魔法冰泉"), 4, research("少量")), new RecipeItem(findItemByName("矿盐"), 4, research("少量")), new RecipeItem(findItemByName("黑炭"), 4, research("少量"))));
        RECIPE_LIST.add(new Recipe(59, "焦炭树枝", recipeType("研制"), habitat("火山"), new RecipeSell(104, 114, 124, 87, 1.816092f), new RecipeRecovery(20, 22, 24, 31), new RecipeItem(findItemByName("矿石碎片"), 1, research("少量")), new RecipeItem(findItemByName("黑炭"), 3, research("少量")), new RecipeItem(findItemByName("坚硬荆棘"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(60, "焦炭虫", recipeType("研制"), habitat("火山"), new RecipeSell(408, 448, 489, 285, 2.77193f), new RecipeRecovery(81, 89, 97, 122), new RecipeItem(findItemByName("黑炭"), 3, research("少量")), new RecipeItem(findItemByName("火溶虫"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(61, "鸟笼", recipeType("研制"), habitat("湖泊"), new RecipeSell(825, 907, 990, 580, 2.812069f), new RecipeRecovery(165, 181, 198, 247), new RecipeItem(findItemByName("星辰珊瑚"), 1, research("少量")), new RecipeItem(findItemByName("炽热蚯蚓"), 1, research("少量")), new RecipeItem(findItemByName("坚硬荆棘"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(62, "星空粉", recipeType("研制"), habitat("湖泊"), new RecipeSell(680, 748, 816, 448, 2.982143f), new RecipeRecovery(136, 149, 163, 204), new RecipeItem(findItemByName("星辰珊瑚"), 1, research("少量")), new RecipeItem(findItemByName("岩蛭"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(63, "火爆面包", recipeType("研制"), habitat("山地"), new RecipeSell(624, 686, 748, 390, 3.107692f), new RecipeRecovery(124, 137, 149, 187), new RecipeItem(findItemByName("甜味黏土"), 1, research("少量")), new RecipeItem(findItemByName("火结晶"), 1, research("少量")), new RecipeItem(findItemByName("黄金小麦"), 1, research("少量")), new RecipeItem(findItemByName("辛辣辣椒"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(64, "火锅底料", recipeType("研制"), habitat("火山"), new RecipeSell(584, 642, 700, 435, 2.685057f), new RecipeRecovery(116, 128, 140, 175), new RecipeItem(findItemByName("火结晶"), 1, research("少量")), new RecipeItem(findItemByName("坚硬荆棘"), 1, research("少量")), new RecipeItem(findItemByName("辛辣辣椒"), 1, research("少量")), new RecipeItem(findItemByName("蜜虫"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(65, "火爆药粉", recipeType("研制"), habitat("草原"), new RecipeSell(536, 589, 643, 353, 2.963173f), new RecipeRecovery(107, 117, 128, 160), new RecipeItem(findItemByName("微风粉尘"), 1, research("少量")), new RecipeItem(findItemByName("坚硬的喙"), 1, research("少量")), new RecipeItem(findItemByName("辛辣辣椒"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(66, "辣椒盐", recipeType("研制"), habitat("火山"), new RecipeSell(552, 607, 662, 348, 3.091954f), new RecipeRecovery(110, 121, 132, 165), new RecipeItem(findItemByName("矿盐"), 1, research("少量")), new RecipeItem(findItemByName("辛辣辣椒"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(67, "甜辣酱", recipeType("研制"), habitat("火山"), new RecipeSell(592, 651, 710, 413, 2.837772f), new RecipeRecovery(118, 130, 142, 177), new RecipeItem(findItemByName("血浆果"), 1, research("少量")), new RecipeItem(findItemByName("辛辣辣椒"), 1, research("少量")), new RecipeItem(findItemByName("蜜虫"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(68, "火辣蚯蚓", recipeType("研制"), habitat("火山"), new RecipeSell(656, 721, 787, 458, 2.838428f), new RecipeRecovery(131, 144, 157, 196), new RecipeItem(findItemByName("炽热蚯蚓"), 1, research("少量")), new RecipeItem(findItemByName("辛辣辣椒"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(69, "百变黏土", recipeType("研制"), habitat("山地"), new RecipeSell(88, 96, 105, 75, 1.693333f), new RecipeRecovery(17, 19, 21, 26), new RecipeItem(findItemByName("甜味黏土"), 3, research("少量")), new RecipeItem(findItemByName("息土"), 5, research("大量"))));
        RECIPE_LIST.add(new Recipe(70, "蜜罐", recipeType("研制"), habitat("草原"), new RecipeSell(248, 272, 297, 188, 2.18617f), new RecipeRecovery(49, 54, 59, 74), new RecipeItem(findItemByName("蜂蜡"), 4, research("少量")), new RecipeItem(findItemByName("息土"), 2, research("少量")), new RecipeItem(findItemByName("蜜虫"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(71, "长明灯", recipeType("研制"), habitat("火山"), new RecipeSell(488, 536, 585, 360, 2.705556f), new RecipeRecovery(97, 107, 117, 146), new RecipeItem(findItemByName("龙卷斑蝶"), 1, research("少量")), new RecipeItem(findItemByName("长明草"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(72, "贝壳粉", recipeType("研制"), habitat("山地"), new RecipeSell(240, 264, 288, 190, 1.994737f), new RecipeRecovery(48, 52, 57, 72), new RecipeItem(findItemByName("甲贝"), 1, research("少量")), new RecipeItem(findItemByName("涤辰砂"), 5, research("大量"))));
        RECIPE_LIST.add(new Recipe(73, "研磨粉", recipeType("研制"), habitat("火山"), new RecipeSell(504, 554, 604, 373, 2.402145f), new RecipeRecovery(100, 110, 120, 151), new RecipeItem(findItemByName("涤辰砂"), 1, research("少量")), new RecipeItem(findItemByName("折光兰"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(74, "星辰珠", recipeType("研制"), habitat("湖泊"), new RecipeSell(696, 765, 835, 463, 2.933045f), new RecipeRecovery(139, 153, 167, 208), new RecipeItem(findItemByName("涤辰砂"), 1, research("少量")), new RecipeItem(findItemByName("星辰珊瑚"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(75, "棕色墨水", recipeType("研制"), habitat("湖泊"), new RecipeSell(184, 202, 220, 145, 2f), new RecipeRecovery(36, 40, 44, 55), new RecipeItem(findItemByName("魔法冰泉"), 2, research("少量")), new RecipeItem(findItemByName("矿盐"), 3, research("少量")), new RecipeItem(findItemByName("铜簇"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(76, "提纯铜锭", recipeType("研制"), habitat("草原"), new RecipeSell(272, 299, 326, 192, 2.302083f), new RecipeRecovery(54, 59, 65, 81), new RecipeItem(findItemByName("铜簇"), 4, research("少量")), new RecipeItem(findItemByName("息土"), 1, research("少量")), new RecipeItem(findItemByName("岩蛭"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(77, "星辰晶簇", recipeType("研制"), habitat("山地"), new RecipeSell(696, 765, 835, 463, 2.933045f), new RecipeRecovery(139, 153, 167, 208), new RecipeItem(findItemByName("铜簇"), 1, research("少量")), new RecipeItem(findItemByName("星辰珊瑚"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(78, "晶化蚯蚓", recipeType("研制"), habitat("山地"), new RecipeSell(216, 237, 259, 155, 2.445161f), new RecipeRecovery(43, 47, 51, 64), new RecipeItem(findItemByName("铜簇"), 1, research("少量")), new RecipeItem(findItemByName("炽热蚯蚓"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(79, "荆棘耳环", recipeType("研制"), habitat("火山"), new RecipeSell(248, 272, 297, 187, 2.149733f), new RecipeRecovery(49, 54, 59, 74), new RecipeItem(findItemByName("矿石碎片"), 5, research("大量")), new RecipeItem(findItemByName("铜簇"), 3, research("少量")), new RecipeItem(findItemByName("坚硬荆棘"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(80, "地狱野火", recipeType("研制"), habitat("火山"), new RecipeSell(216, 237, 259, 180, 2.055556f), new RecipeRecovery(43, 47, 51, 64), new RecipeItem(findItemByName("液态滚石"), 1, research("少量")), new RecipeItem(findItemByName("黑炭"), 3, research("少量")), new RecipeItem(findItemByName("厄运蘑菇"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(81, "燃烧宝石", recipeType("研制"), habitat("火山"), new RecipeSell(296, 325, 355, 210, 2.357143f), new RecipeRecovery(59, 65, 71, 88), new RecipeItem(findItemByName("液态滚石"), 3, research("少量")), new RecipeItem(findItemByName("黑炭"), 1, research("少量")), new RecipeItem(findItemByName("长明草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(82, "高温溶剂", recipeType("研制"), habitat("火山"), new RecipeSell(448, 492, 537, 295, 2.932203f), new RecipeRecovery(89, 98, 107, 134), new RecipeItem(findItemByName("液态滚石"), 1, research("少量")), new RecipeItem(findItemByName("火溶虫"), 1, research("少量")), new RecipeItem(findItemByName("岩蛭"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(83, "沙尘暴", recipeType("研制"), habitat("火山"), new RecipeSell(1395, 1534, 1674, 984, 2.905488f), new RecipeRecovery(279, 306, 334, 418), new RecipeItem(findItemByName("息土"), 7, research("大量")), new RecipeItem(findItemByName("龙卷斑蝶"), 3, research("少量")), new RecipeItem(findItemByName("沙漠瓢虫"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(84, "“丰盛”晚餐", recipeType("研制"), habitat("火山"), new RecipeSell(1350, 1485, 1620, 900, 3.077778f), new RecipeRecovery(270, 297, 324, 405), new RecipeItem(findItemByName("炽热蚯蚓"), 1, research("少量")), new RecipeItem(findItemByName("火溶虫"), 1, research("少量")), new RecipeItem(findItemByName("岩蛭"), 6, research("大量")), new RecipeItem(findItemByName("蜜虫"), 1, research("少量")), new RecipeItem(findItemByName("沙漠瓢虫"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(85, "惰性凝液", recipeType("研制"), habitat("湖泊"), new RecipeSell(384, 422, 460, 285, 2.294737f), new RecipeRecovery(76, 84, 92, 115), new RecipeItem(findItemByName("魔法冰泉"), 6, research("大量")), new RecipeItem(findItemByName("重水"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(86, "淬火甲壳", recipeType("研制"), habitat("湖泊"), new RecipeSell(448, 492, 537, 295, 2.579661f), new RecipeRecovery(89, 98, 107, 134), new RecipeItem(findItemByName("液态滚石"), 1, research("少量")), new RecipeItem(findItemByName("重水"), 2, research("少量")), new RecipeItem(findItemByName("甲贝"), 6, research("大量"))));
        RECIPE_LIST.add(new Recipe(87, "璀璨珍珠", recipeType("研制"), habitat("湖泊"), new RecipeSell(1395, 1534, 1674, 980, 2.913265f), new RecipeRecovery(279, 306, 334, 418), new RecipeItem(findItemByName("重水"), 1, research("少量")), new RecipeItem(findItemByName("涤辰砂"), 5, research("大量")), new RecipeItem(findItemByName("珍珠果"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(88, "魔法火坑", recipeType("研制"), habitat("山地"), new RecipeSell(480, 528, 576, 302, 2.86755f), new RecipeRecovery(96, 105, 115, 144), new RecipeItem(findItemByName("矿石碎片"), 1, research("少量")), new RecipeItem(findItemByName("自燃石"), 2, research("少量")), new RecipeItem(findItemByName("坚硬荆棘"), 1, research("少量")), new RecipeItem(findItemByName("长明草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(89, "火焰爆弹", recipeType("研制"), habitat("火山"), new RecipeSell(360, 396, 432, 270, 2.281481f), new RecipeRecovery(72, 79, 86, 108), new RecipeItem(findItemByName("液态滚石"), 2, research("少量")), new RecipeItem(findItemByName("自燃石"), 2, research("少量")), new RecipeItem(findItemByName("黑炭"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(90, "恒温泉水", recipeType("研制"), habitat("湖泊"), new RecipeSell(408, 448, 489, 255, 2.717647f), new RecipeRecovery(81, 89, 97, 122), new RecipeItem(findItemByName("重水"), 1, research("少量")), new RecipeItem(findItemByName("自燃石"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(91, "定时“炸弹”", recipeType("研制"), habitat("火山"), new RecipeSell(432, 475, 518, 270, 2.740741f), new RecipeRecovery(86, 95, 103, 129), new RecipeItem(findItemByName("自燃石"), 3, research("少量")), new RecipeItem(findItemByName("血浆果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(92, "火龙卷", recipeType("研制"), habitat("火山"), new RecipeSell(360, 396, 432, 265, 2.581132f), new RecipeRecovery(72, 79, 86, 108), new RecipeItem(findItemByName("自燃石"), 1, research("少量")), new RecipeItem(findItemByName("龙卷斑蝶"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(93, "仙叶花洒", recipeType("研制"), habitat("草原"), new RecipeSell(320, 352, 384, 225, 2.48f), new RecipeRecovery(64, 70, 76, 96), new RecipeItem(findItemByName("棉雾气团"), 1, research("少量")), new RecipeItem(findItemByName("生命之叶"), 2, research("少量")), new RecipeItem(findItemByName("降雨水仙"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(94, "蜂蜜药膏", recipeType("研制"), habitat("草原"), new RecipeSell(408, 448, 489, 270, 2.659259f), new RecipeRecovery(81, 89, 97, 122), new RecipeItem(findItemByName("蜂蜡"), 5, research("大量")), new RecipeItem(findItemByName("生命之叶"), 1, research("少量")), new RecipeItem(findItemByName("蜜虫"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(95, "蜂箱", recipeType("研制"), habitat("山地"), new RecipeSell(424, 466, 508, 314, 2.697452f), new RecipeRecovery(84, 93, 101, 127), new RecipeItem(findItemByName("坚硬荆棘"), 7, research("大量")), new RecipeItem(findItemByName("干涸地蔓"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(96, "贝壳项链", recipeType("研制"), habitat("湖泊"), new RecipeSell(1500, 1650, 1800, 910, 3.352747f), new RecipeRecovery(300, 330, 360, 450), new RecipeItem(findItemByName("甲贝"), 4, research("少量")), new RecipeItem(findItemByName("风滚草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(97, "沙滩项链", recipeType("研制"), habitat("湖泊"), new RecipeSell(1927, 2119, 2312, 1225, 3.141224f), new RecipeRecovery(385, 423, 462, 578), new RecipeItem(findItemByName("甲贝"), 1, research("少量")), new RecipeItem(findItemByName("风滚草"), 1, research("少量")), new RecipeItem(findItemByName("珍珠果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(98, "易燃草堆", recipeType("研制"), habitat("山地"), new RecipeSell(1297, 1426, 1556, 865, 3.087861f), new RecipeRecovery(259, 285, 311, 389), new RecipeItem(findItemByName("黑炭"), 1, research("少量")), new RecipeItem(findItemByName("风滚草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(99, "生命之绳", recipeType("研制"), habitat("草原"), new RecipeSell(1710, 1881, 2052, 1090, 3.162385f), new RecipeRecovery(342, 376, 410, 513), new RecipeItem(findItemByName("生命之叶"), 3, research("少量")), new RecipeItem(findItemByName("风滚草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(100, "希望项链", recipeType("研制"), habitat("草原"), new RecipeSell(1837, 2020, 2204, 1290, 2.852713f), new RecipeRecovery(367, 404, 440, 551), new RecipeItem(findItemByName("生命之叶"), 1, research("少量")), new RecipeItem(findItemByName("风滚草"), 1, research("少量")), new RecipeItem(findItemByName("珍珠果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(101, "烈焰火球", recipeType("研制"), habitat("火山"), new RecipeSell(1710, 1881, 2052, 1090, 3.162385f), new RecipeRecovery(342, 376, 410, 513), new RecipeItem(findItemByName("火溶虫"), 1, research("少量")), new RecipeItem(findItemByName("风滚草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(102, "珍珠项链", recipeType("研制"), habitat("湖泊"), new RecipeSell(1815, 1996, 2178, 1210, 3.006612f), new RecipeRecovery(363, 399, 435, 544), new RecipeItem(findItemByName("风滚草"), 1, research("少量")), new RecipeItem(findItemByName("珍珠果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(103, "强韧绳子", recipeType("研制"), habitat("草原"), new RecipeSell(2506, 2756, 3007, 1790, 2.819553f), new RecipeRecovery(501, 551, 601, 751), new RecipeItem(findItemByName("黑海带"), 1, research("少量")), new RecipeItem(findItemByName("干涸地蔓"), 1, research("少量")), new RecipeItem(findItemByName("风滚草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(104, "液态火焰", recipeType("研制"), habitat("湖泊"), new RecipeSell(1762, 1938, 2114, 1175, 3.011915f), new RecipeRecovery(352, 387, 422, 528), new RecipeItem(findItemByName("重水"), 1, research("少量")), new RecipeItem(findItemByName("火溶虫"), 1, research("少量")), new RecipeItem(findItemByName("火焰麦穗"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(105, "燃烧草堆", recipeType("研制"), habitat("山地"), new RecipeSell(2520, 2772, 3024, 1715, 2.959184f), new RecipeRecovery(504, 554, 604, 756), new RecipeItem(findItemByName("黑炭"), 1, research("少量")), new RecipeItem(findItemByName("风滚草"), 1, research("少量")), new RecipeItem(findItemByName("火焰麦穗"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(106, "火焰麦酒", recipeType("研制"), habitat("草原"), new RecipeSell(1560, 1716, 1872, 992, 3.189516f), new RecipeRecovery(312, 343, 374, 468), new RecipeItem(findItemByName("黄金小麦"), 1, research("少量")), new RecipeItem(findItemByName("幻梦菇"), 5, research("大量")), new RecipeItem(findItemByName("火焰麦穗"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(107, "火树银花", recipeType("研制"), habitat("湖泊"), new RecipeSell(2471, 2718, 2965, 1608, 3.099502f), new RecipeRecovery(494, 543, 593, 741), new RecipeItem(findItemByName("星辰珊瑚"), 1, research("少量")), new RecipeItem(findItemByName("火溶虫"), 1, research("少量")), new RecipeItem(findItemByName("干涸地蔓"), 1, research("少量")), new RecipeItem(findItemByName("火焰麦穗"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(108, "速疗药剂", recipeType("研制"), habitat("草原"), new RecipeSell(1147, 1261, 1376, 806, 2.692308f), new RecipeRecovery(229, 252, 275, 344), new RecipeItem(findItemByName("妖精粉尘"), 1, research("少量")), new RecipeItem(findItemByName("生命之叶"), 6, research("大量")), new RecipeItem(findItemByName("魔法亓草"), 7, research("大量"))));
        RECIPE_LIST.add(new Recipe(109, "妖精礼炮", recipeType("研制"), habitat("草原"), new RecipeSell(1522, 1674, 1826, 924, 3.137446f), new RecipeRecovery(304, 334, 365, 456), new RecipeItem(findItemByName("妖精粉尘"), 3, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 8, research("大量")), new RecipeItem(findItemByName("喷射孢子"), 5, research("大量"))));
        RECIPE_LIST.add(new Recipe(110, "隐形药剂", recipeType("研制"), habitat("草原"), new RecipeSell(1245, 1369, 1494, 878, 2.843964f), new RecipeRecovery(249, 273, 298, 373), new RecipeItem(findItemByName("妖精粉尘"), 2, research("少量")), new RecipeItem(findItemByName("折光兰"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(111, "除厄灵药", recipeType("研制"), habitat("草原"), new RecipeSell(1605, 1765, 1926, 974, 3.161191f), new RecipeRecovery(321, 353, 385, 481), new RecipeItem(findItemByName("妖精粉尘"), 3, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 8, research("大量")), new RecipeItem(findItemByName("厄运蘑菇"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(112, "史莱姆王冠", recipeType("研制"), habitat("山地"), new RecipeSell(216, 237, 259, 155, 2.212903f), new RecipeRecovery(43, 47, 51, 64), new RecipeItem(findItemByName("甜味黏土"), 2, research("少量")), new RecipeItem(findItemByName("魔法冰泉"), 3, research("少量")), new RecipeItem(findItemByName("晶海星"), 5, research("大量"))));
        RECIPE_LIST.add(new Recipe(113, "祝福石板", recipeType("研制"), habitat("山地"), new RecipeSell(1852, 2037, 2222, 1236, 3f), new RecipeRecovery(370, 407, 444, 555), new RecipeItem(findItemByName("晶海星"), 1, research("少量")), new RecipeItem(findItemByName("妖精粉尘"), 1, research("少量")), new RecipeItem(findItemByName("刻金石板"), 1, research("少量")), new RecipeItem(findItemByName("火焰麦穗"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(114, "鎏金粉", recipeType("研制"), habitat("山地"), new RecipeSell(480, 528, 576, 300, 2.72f), new RecipeRecovery(96, 105, 115, 144), new RecipeItem(findItemByName("液态滚石"), 1, research("少量")), new RecipeItem(findItemByName("刻金石板"), 1, research("少量")), new RecipeItem(findItemByName("涤辰砂"), 5, research("大量"))));
        RECIPE_LIST.add(new Recipe(115, "血字石板", recipeType("研制"), habitat("山地"), new RecipeSell(464, 510, 556, 345, 2.585507f), new RecipeRecovery(92, 102, 111, 139), new RecipeItem(findItemByName("刻金石板"), 1, research("少量")), new RecipeItem(findItemByName("血浆果"), 1, research("少量")), new RecipeItem(findItemByName("火溶虫"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(116, "神秘符文", recipeType("研制"), habitat("山地"), new RecipeSell(280, 308, 336, 210, 2.509524f), new RecipeRecovery(56, 61, 67, 84), new RecipeItem(findItemByName("刻金石板"), 1, research("少量")), new RecipeItem(findItemByName("炽热蚯蚓"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(117, "镶金罐子", recipeType("研制"), habitat("山地"), new RecipeSell(416, 457, 499, 274, 2.580292f), new RecipeRecovery(83, 91, 99, 124), new RecipeItem(findItemByName("刻金石板"), 1, research("少量")), new RecipeItem(findItemByName("息土"), 2, research("少量")), new RecipeItem(findItemByName("古代页岩"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(118, "诅咒遗物", recipeType("研制"), habitat("山地"), new RecipeSell(376, 413, 451, 280, 2.360714f), new RecipeRecovery(75, 82, 90, 112), new RecipeItem(findItemByName("刻金石板"), 1, research("少量")), new RecipeItem(findItemByName("息土"), 5, research("大量")), new RecipeItem(findItemByName("古代页岩"), 1, research("少量")), new RecipeItem(findItemByName("厄运蘑菇"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(119, "护身甲片", recipeType("研制"), habitat("山地"), new RecipeSell(1365, 1501, 1638, 910, 2.8f), new RecipeRecovery(273, 300, 327, 409), new RecipeItem(findItemByName("液态滚石"), 8, research("大量")), new RecipeItem(findItemByName("深谷坚石"), 2, research("少量")), new RecipeItem(findItemByName("甲贝"), 6, research("大量"))));
        RECIPE_LIST.add(new Recipe(120, "厄运神像", recipeType("研制"), habitat("火山"), new RecipeSell(1762, 1938, 2114, 1070, 3.099065f), new RecipeRecovery(352, 387, 422, 528), new RecipeItem(findItemByName("深谷坚石"), 2, research("少量")), new RecipeItem(findItemByName("古代页岩"), 6, research("大量")), new RecipeItem(findItemByName("厄运蘑菇"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(121, "苦痛神像", recipeType("研制"), habitat("山地"), new RecipeSell(1597, 1756, 1916, 972, 3.169753f), new RecipeRecovery(319, 351, 383, 479), new RecipeItem(findItemByName("深谷坚石"), 2, research("少量")), new RecipeItem(findItemByName("古代页岩"), 3, research("少量")), new RecipeItem(findItemByName("坚硬荆棘"), 6, research("大量"))));
        RECIPE_LIST.add(new Recipe(122, "虫神像", recipeType("研制"), habitat("山地"), new RecipeSell(1890, 2079, 2268, 1330, 2.790977f), new RecipeRecovery(378, 415, 453, 567), new RecipeItem(findItemByName("深谷坚石"), 3, research("少量")), new RecipeItem(findItemByName("古代页岩"), 2, research("少量")), new RecipeItem(findItemByName("沙漠瓢虫"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(123, "古代秘药", recipeType("研制"), habitat("草原"), new RecipeSell(1357, 1492, 1628, 954, 2.918239f), new RecipeRecovery(271, 298, 325, 407), new RecipeItem(findItemByName("蜂蜡"), 9, research("大量")), new RecipeItem(findItemByName("古树花粉"), 2, research("少量")), new RecipeItem(findItemByName("龙卷斑蝶"), 1, research("少量")), new RecipeItem(findItemByName("沙漠瓢虫"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(124, "奇迹粉尘", recipeType("研制"), habitat("草原"), new RecipeSell(1402, 1542, 1682, 988, 2.656883f), new RecipeRecovery(280, 308, 336, 420), new RecipeItem(findItemByName("古树花粉"), 4, research("少量")), new RecipeItem(findItemByName("妖精粉尘"), 2, research("少量")), new RecipeItem(findItemByName("生命之叶"), 1, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(125, "万用药", recipeType("研制"), habitat("草原"), new RecipeSell(1252, 1377, 1502, 882, 2.693878f), new RecipeRecovery(250, 275, 300, 375), new RecipeItem(findItemByName("古树花粉"), 6, research("大量")), new RecipeItem(findItemByName("妖精粉尘"), 1, research("少量")), new RecipeItem(findItemByName("魔法亓草"), 9, research("大量"))));
        RECIPE_LIST.add(new Recipe(126, "疗伤中药", recipeType("研制"), habitat("草原"), new RecipeSell(392, 431, 470, 290, 2.465517f), new RecipeRecovery(78, 86, 94, 117), new RecipeItem(findItemByName("古树花粉"), 1, research("少量")), new RecipeItem(findItemByName("生命之叶"), 1, research("少量")), new RecipeItem(findItemByName("蜜虫"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(127, "呛鼻粉尘", recipeType("研制"), habitat("草原"), new RecipeSell(408, 448, 489, 270, 2.837037f), new RecipeRecovery(81, 89, 97, 122), new RecipeItem(findItemByName("古树花粉"), 1, research("少量")), new RecipeItem(findItemByName("龙卷斑蝶"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(128, "地藏", recipeType("研制"), habitat("山地"), new RecipeSell(376, 413, 451, 264, 2.42803f), new RecipeRecovery(75, 82, 90, 112), new RecipeItem(findItemByName("矿石碎片"), 6, research("大量")), new RecipeItem(findItemByName("刻金石板"), 1, research("少量")), new RecipeItem(findItemByName("息土"), 2, research("少量")), new RecipeItem(findItemByName("化石鱼骨"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(129, "化石粉", recipeType("研制"), habitat("湖泊"), new RecipeSell(432, 475, 518, 305, 2.419672f), new RecipeRecovery(86, 95, 103, 129), new RecipeItem(findItemByName("涤辰砂"), 1, research("少量")), new RecipeItem(findItemByName("化石鱼骨"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(130, "火药粉末", recipeType("研制"), habitat("火山"), new RecipeSell(504, 554, 604, 315, 2.71746f), new RecipeRecovery(100, 110, 120, 151), new RecipeItem(findItemByName("化石鱼骨"), 3, research("少量")), new RecipeItem(findItemByName("黑炭"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(131, "魔力冰晶", recipeType("研制"), habitat("湖泊"), new RecipeSell(1537, 1690, 1844, 935, 3.265241f), new RecipeRecovery(307, 338, 368, 461), new RecipeItem(findItemByName("魔法冰泉"), 7, research("大量")), new RecipeItem(findItemByName("深海结晶"), 2, research("少量")), new RecipeItem(findItemByName("丛云果"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(132, "克莱因金属", recipeType("研制"), habitat("山地"), new RecipeSell(1065, 1171, 1278, 710, 2.842254f), new RecipeRecovery(213, 234, 255, 319), new RecipeItem(findItemByName("矿石碎片"), 4, research("少量")), new RecipeItem(findItemByName("铜簇"), 2, research("少量")), new RecipeItem(findItemByName("深海结晶"), 2, research("少量")), new RecipeItem(findItemByName("岩蛭"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(133, "海洋之心", recipeType("研制"), habitat("湖泊"), new RecipeSell(1725, 1897, 2070, 1099, 3.161056f), new RecipeRecovery(345, 379, 414, 517), new RecipeItem(findItemByName("晶海星"), 1, research("少量")), new RecipeItem(findItemByName("甲贝"), 1, research("少量")), new RecipeItem(findItemByName("深海结晶"), 1, research("少量")), new RecipeItem(findItemByName("星辰珊瑚"), 1, research("少量")), new RecipeItem(findItemByName("珍珠果"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(134, "元素精华", recipeType("研制"), habitat("火山"), new RecipeSell(1432, 1575, 1718, 914, 2.929978f), new RecipeRecovery(286, 315, 343, 429), new RecipeItem(findItemByName("液态滚石"), 6, research("大量")), new RecipeItem(findItemByName("息土"), 7, research("大量")), new RecipeItem(findItemByName("深海结晶"), 2, research("少量")), new RecipeItem(findItemByName("生命之叶"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(135, "深海精华素", recipeType("研制"), habitat("湖泊"), new RecipeSell(1185, 1303, 1422, 755, 2.933775f), new RecipeRecovery(237, 260, 284, 355), new RecipeItem(findItemByName("重水"), 5, research("大量")), new RecipeItem(findItemByName("甲贝"), 4, research("少量")), new RecipeItem(findItemByName("深海结晶"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(136, "化石结晶", recipeType("研制"), habitat("湖泊"), new RecipeSell(1530, 1683, 1836, 975, 2.933333f), new RecipeRecovery(306, 336, 367, 459), new RecipeItem(findItemByName("重水"), 3, research("少量")), new RecipeItem(findItemByName("化石鱼骨"), 5, research("大量")), new RecipeItem(findItemByName("深海结晶"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(137, "梅林勋章", recipeType("研制"), habitat("草原"), new RecipeSell(744, 818, 892, 466, 3.004292f), new RecipeRecovery(148, 163, 178, 223), new RecipeItem(findItemByName("彩虹羽翼"), 1, research("少量")), new RecipeItem(findItemByName("晶海星"), 1, research("少量")), new RecipeItem(findItemByName("干涸砂砾"), 1, research("少量")), new RecipeItem(findItemByName("折光兰"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(138, "筑城砂砖", recipeType("研制"), habitat("山地"), new RecipeSell(376, 413, 451, 280, 2.289286f), new RecipeRecovery(75, 82, 90, 112), new RecipeItem(findItemByName("矿石碎片"), 5, research("大量")), new RecipeItem(findItemByName("矿盐"), 5, research("大量")), new RecipeItem(findItemByName("干涸砂砾"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(139, "可塑砂泥", recipeType("研制"), habitat("湖泊"), new RecipeSell(424, 466, 508, 280, 2.575f), new RecipeRecovery(84, 93, 101, 127), new RecipeItem(findItemByName("重水"), 1, research("少量")), new RecipeItem(findItemByName("涤辰砂"), 3, research("少量")), new RecipeItem(findItemByName("干涸砂砾"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(140, "沙漏", recipeType("研制"), habitat("山地"), new RecipeSell(424, 466, 508, 282, 2.560284f), new RecipeRecovery(84, 93, 101, 127), new RecipeItem(findItemByName("息土"), 1, research("少量")), new RecipeItem(findItemByName("干涸砂砾"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(141, "厄运沙包", recipeType("研制"), habitat("火山"), new RecipeSell(1665, 1831, 1998, 1170, 2.871795f), new RecipeRecovery(333, 366, 399, 499), new RecipeItem(findItemByName("干涸砂砾"), 2, research("少量")), new RecipeItem(findItemByName("厄运蘑菇"), 1, research("少量")), new RecipeItem(findItemByName("黑海带"), 1, research("少量")), new RecipeItem(findItemByName("干涸地蔓"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(142, "砂蔓牢笼", recipeType("研制"), habitat("火山"), new RecipeSell(488, 536, 585, 360, 2.405556f), new RecipeRecovery(97, 107, 117, 146), new RecipeItem(findItemByName("干涸砂砾"), 3, research("少量")), new RecipeItem(findItemByName("干涸地蔓"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(143, "不灭的火种", recipeType("研制"), habitat("火山"), new RecipeSell(1245, 1369, 1494, 875, 2.657143f), new RecipeRecovery(249, 273, 298, 373), new RecipeItem(findItemByName("火结晶"), 3, research("少量")), new RecipeItem(findItemByName("闪亮红砂"), 5, research("大量")), new RecipeItem(findItemByName("日光石"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(144, "五彩晶片", recipeType("研制"), habitat("草原"), new RecipeSell(885, 973, 1062, 566, 2.925795f), new RecipeRecovery(177, 194, 212, 265), new RecipeItem(findItemByName("晶海星"), 1, research("少量")), new RecipeItem(findItemByName("妖精粉尘"), 1, research("少量")), new RecipeItem(findItemByName("日光石"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(145, "放大镜片", recipeType("研制"), habitat("湖泊"), new RecipeSell(1380, 1518, 1656, 879, 2.934016f), new RecipeRecovery(276, 303, 331, 414), new RecipeItem(findItemByName("晶海星"), 9, research("大量")), new RecipeItem(findItemByName("涤辰砂"), 3, research("少量")), new RecipeItem(findItemByName("日光石"), 2, research("少量"))));
        RECIPE_LIST.add(new Recipe(146, "折光镜", recipeType("研制"), habitat("草原"), new RecipeSell(1575, 1732, 1890, 956, 3.254184f), new RecipeRecovery(315, 346, 378, 472), new RecipeItem(findItemByName("晶海星"), 3, research("少量")), new RecipeItem(findItemByName("日光石"), 2, research("少量")), new RecipeItem(findItemByName("折光兰"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(147, "闲者石", recipeType("研制"), habitat("山地"), new RecipeSell(1507, 1657, 1808, 1005, 2.799005f), new RecipeRecovery(301, 331, 361, 452), new RecipeItem(findItemByName("液态滚石"), 6, research("大量")), new RecipeItem(findItemByName("自燃石"), 3, research("少量")), new RecipeItem(findItemByName("深谷坚石"), 1, research("少量")), new RecipeItem(findItemByName("日光石"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(148, "日光粉", recipeType("研制"), habitat("湖泊"), new RecipeSell(1530, 1683, 1836, 1020, 2.8f), new RecipeRecovery(306, 336, 367, 459), new RecipeItem(findItemByName("涤辰砂"), 6, research("大量")), new RecipeItem(findItemByName("日光石"), 3, research("少量"))));
        RECIPE_LIST.add(new Recipe(149, "热风宝石", recipeType("研制"), habitat("火山"), new RecipeSell(1950, 2145, 2340, 1300, 2.992308f), new RecipeRecovery(390, 429, 468, 585), new RecipeItem(findItemByName("日光石"), 1, research("少量")), new RecipeItem(findItemByName("火焰麦穗"), 1, research("少量")), new RecipeItem(findItemByName("龙卷斑蝶"), 1, research("少量"))));
        RECIPE_LIST.add(new Recipe(150, "珠光石", recipeType("研制"), habitat("火山"), new RecipeSell(990, 1089, 1188, 630, 3.222222f), new RecipeRecovery(198, 217, 237, 297), new RecipeItem(findItemByName("日光石"), 1, research("少量")), new RecipeItem(findItemByName("珍珠果"), 1, research("少量"))));

    }

    private static EItemType itemType(String strItemType) {
        return EItemType.getByCNName(strItemType);
    }

    private static EHabitat habitat(String strHabitat) {
        return EHabitat.getByCNName(strHabitat);
    }

    private static ECollectPlace collectPlace(String strCollectPlace) {
        return ECollectPlace.getByCNName(strCollectPlace);
    }

    private static ERecipeType recipeType(String strRecipeType) {
        return ERecipeType.getByCNName(strRecipeType);
    }

    private static EResearch research(String strResearch) {
        return EResearch.getByCNName(strResearch);
    }

    public static List<Recipe> findRecipeByItem(String name) {
        List<Recipe> list = new ArrayList<>();
        for (Recipe recipe : RECIPE_LIST) {
            if (recipe.haveThisItem(findItemByName(name)) != null)
                list.add(recipe);
        }
        return list;
    }

    public static Item findItemByName(String name) {
        for (Item item : ITEM_LIST) {
            if (item.getName().equals(name))
                return item;
        }
        return null;
    }

    public static Item findItemById(EItemType itemType, int id) {
        for (Item item : ITEM_LIST) {
            if (item.getItemType() == itemType)
                if (item.getId() == id)
                    return item;
        }
        return null;
    }

    public static List<Item> searchItemByHabitat(EHabitat habitat) {
        List<Item> list = new ArrayList<>();
        for (Item item : ITEM_LIST) {
            if (item.getHabitat() == habitat)
                list.add(item);
        }
        return list;
    }

    public static List<Item> searchItemByCollectPlace(ECollectPlace collectPlace) {
        List<Item> list = new ArrayList<>();
        for (Item item : ITEM_LIST) {
            if (item.getCollectPlace() == collectPlace)
                list.add(item);
        }
        return list;
    }
}
